### ISSUE TITLE
Set up PostgreSQL Database with Docker

### ISSUE THREAD

**Issue by DiegoB1911** [Crypto-Jaguars/Revo-Backend#1]
## 📝 Description
Create a Docker-based PostgreSQL database setup with proper configuration files and environment variables for development and production environments.

## 📜 Tasks
1. Create a Docker Compose configuration
2. Set up PostgreSQL environment variables
3. Create initialization scripts
4. Configure database volumes
5. Add health checks
6. Document connection details

### Docker Compose Configuration
Create a `docker-compose.yml` file in the project root with the following content:

```yaml
version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: my_postgres_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-mydatabase}
      POSTGRES_USER: ${POSTGRES_USER:-myuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mypassword}
      PGDATA: /data/postgres
    volumes:
      - postgres_data:/data/postgres
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-myuser} -d ${POSTGRES_DB:-mydatabase}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - postgres_network

networks:
  postgres_network:
    driver: bridge

volumes:
  postgres_data:
```

### Environment Variables
Create a `.env` file in the project root:

```env
POSTGRES_DB=mydatabase
POSTGRES_USER=myuser
POSTGRES_PASSWORD=mypassword
POSTGRES_HOST=localhost
POSTGRES_PORT=5432
```

### Database Initialization Script
Create a directory `init-scripts` and add `01-init.sql`:

```sql
-- Create extensions if needed
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Create example table
CREATE TABLE IF NOT EXISTS example_table (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Add any initial data if needed
INSERT INTO example_table (name) VALUES ('Example Record');
```

## Connection Details
- Host: `localhost` (or `postgres` if connecting from another container)
- Port: `5432`
- Database: `mydatabase`
- Username: `myuser`
- Password: `mypassword`

## Usage Instructions
1. Make sure Docker and Docker Compose are installed
2. Clone the repository
3. Copy the `.env.example` to `.env` and adjust values if needed
4. Run:
   ```bash
   docker-compose up -d
   ```
5. Verify the container is running:
   ```bash
   docker-compose ps
   ```

## 📋 Additional Notes
- Data is persisted in a named volume `postgres_data`
- Database initialization scripts in `init-scripts` run automatically on first startup
- Health checks ensure the database is ready before accepting connections
- The database is accessible on port 5432

We will be very happy to see your applications, good luck! 🌾
